[package]
name = "german-holidays"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Lars Aepler"]
license = "GPLv3"
description = "Check if a date is a german holiday"
keywords = ["holiday", "datetime"]
