[package]
name = "german-holidays"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Lars Aepler"]
repository = "https://github.com/laepl/german-holidays"
license = "GPLv3"
description = "Provide functions to work with German holidays"
keywords = ["holiday", "datetime"]
