[package]
name = "german-holidays"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Lars Aepler"]
license = "GPLv3"
description = "Provide functions to work with German holidays"
keywords = ["holiday", "datetime"]
