[de]
1 = "Neujahr"
2 = "Heilige Drei Könige"
3 = "Internationaler Frauentag"
4 = "Karfreitag"
5 = "Ostersonntag"
6 = "Ostermontag"
7 = "Tag der Arbeit"
8 = "Christi Himmelfahrt"
9 = "Pfingstmontag"
10 = "Fronleichnam"
11 = "Augsburger Friedensfest"
12= "Mariä Himmelfahrt"
13 = "Weltkindertag"
14 = "Tag der deutschen Einheit"
15 = "Reformationstag"
16 = "Allerheiligen"
17 = "Buß- und Bettag"
18 = "1. Weihnachtsfeiertag"
19 = "2. Weihnachtsfeiertag"

[en]
1 = "New Year"
2 = "Epiphany"
3 = "International Women's Day"
4 = "Good Friday"
5 = "Easter Sunday"
6 = "Easter Monday"
7 = "Labor Day"
8 = "Ascension Day"
9 = "Whitmonday"
10 = "Feast of Corpus Christi"
11 = "Augsburg Peace Festival"
12= "Assumption of Mary"
13 = "Children's Day"
14 = "German Unity Day"
15 = "Reformation Day"
16 = "All Saints' Day"
17 = "Buß- und Bettag"
18 = "Christmas Day"
19 = "Boxing Day"